<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LibraryApi;

class LibraryApiSeeder extends Seeder
{
    public function run(): void
    {
        $apis = [
            [
                'id' => 'API-OPENLIB',
                'name' => 'Open Library Book Search & Covers API',
                'provider' => 'Internet Archive (San Francisco, CA, USA)',
                'category' => 'Global Monograph & Covers',
                'endpoint_template' => 'https://openlibrary.org/search.json?q={query}&limit=12',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => 'Over 30 million bibliographic records, covers, subjects, and authors maintained by the Internet Archive.',
                'docs_url' => 'https://openlibrary.org/developers/api',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-GOOGLEBOOKS',
                'name' => 'Google Books Global Volumes API',
                'provider' => 'Google LLC (Mountain View, CA, USA)',
                'category' => 'Worldwide Books & Previews',
                'endpoint_template' => 'https://www.googleapis.com/books/v1/volumes?q={query}&maxResults=12',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => 'World-spanning index of digitized curriculum books, ISBN metadata, descriptions, and cover art.',
                'docs_url' => 'https://developers.google.com/books',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-CROSSREF',
                'name' => 'Crossref Global Scholarly Works API',
                'provider' => 'Crossref Consortium (Oxford, UK & Lynnfield, USA)',
                'category' => 'Scholarly Research & DOIs',
                'endpoint_template' => 'https://api.crossref.org/works?query={query}&rows=12',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => 'Official registry of 150M+ peer-reviewed journal papers, academic dissertations, and conference proceedings.',
                'docs_url' => 'https://api.crossref.org/',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-OPENALEX',
                'name' => 'OpenAlex Scholarly Knowledge Graph API',
                'provider' => 'OurResearch (Global Non-Profit)',
                'category' => 'Bibliometrics & Citations',
                'endpoint_template' => 'https://api.openalex.org/works?search={query}&per-page=12',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => '250M+ scientific research papers, authors, citations, and institutional research output.',
                'docs_url' => 'https://openalex.org/',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-GUTENDEX',
                'name' => 'Project Gutenberg Classic E-Books (Gutendex)',
                'provider' => 'Project Gutenberg Literary Archive',
                'category' => 'Full-Text Classic Literature & E-Books',
                'endpoint_template' => 'https://gutendex.com/books?search={query}',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => '70,000+ public domain full-text classic textbooks and literature with direct reading downloads.',
                'docs_url' => 'https://gutendex.com/',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-EUROPEPMC',
                'name' => 'Europe PMC Life Sciences & Agriculture API',
                'provider' => 'European Bioinformatics Institute (EMBL-EBI, Hinxton, UK)',
                'category' => 'Agronomy, Medicine & Life Sciences',
                'endpoint_template' => 'https://www.ebi.ac.uk/europepmc/webservices/rest/search?query={query}&format=json&pageSize=12',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => 'Life sciences and agricultural science articles from international institutional repositories.',
                'docs_url' => 'https://europepmc.org/RestfulWebService',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-DOAB',
                'name' => 'Directory of Open Access Books (DOAB)',
                'provider' => 'OAPEN Foundation (The Hague, Netherlands)',
                'category' => 'Peer-Reviewed Academic Books',
                'endpoint_template' => 'https://directory.doabooks.org/rest/search?query={query}&expand=metadata',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => 'Peer-reviewed, open-access academic monographs and scholarly books from world universities.',
                'docs_url' => 'https://directory.doabooks.org/',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-SEMANTICSCHOLAR',
                'name' => 'Semantic Scholar AI Scientific Literature API',
                'provider' => 'Allen Institute for AI (Seattle, WA, USA)',
                'category' => 'Scientific Literature & AI Abstracts',
                'endpoint_template' => 'https://api.semanticscholar.org/graph/v1/paper/search?query={query}&fields=title,authors,year,abstract,citationCount',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => 'Over 200M academic papers, AI-generated TLDR summaries, citation influence graphs, and author profiles.',
                'docs_url' => 'https://www.semanticscholar.org/product/api',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-ARXIV',
                'name' => 'arXiv Open E-Print Archive (Cornell University)',
                'provider' => 'Cornell University & arXiv.org (Ithaca, NY, USA)',
                'category' => 'Quantitative Science & Computer Science',
                'endpoint_template' => 'https://export.arxiv.org/api/query?search_query=all:{query}&start=0&max_results=12',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'xml',
                'description' => '2M+ research e-prints in computer science, mathematics, economics, statistics, and electrical engineering.',
                'docs_url' => 'https://info.arxiv.org/help/api/index.html',
                'status' => 'Active',
                'is_preset' => true,
            ],
            [
                'id' => 'API-LOC',
                'name' => 'Library of Congress National Catalog (loc.gov)',
                'provider' => 'Library of Congress (Washington, D.C., USA)',
                'category' => 'National Catalog & MARC Authority',
                'endpoint_template' => 'https://www.loc.gov/search/?q={query}&fo=json',
                'auth_type' => 'Free Open Access',
                'api_key' => null,
                'response_type' => 'json',
                'description' => 'Official national authority classification records, LCCN data, and historical digitized collection items.',
                'docs_url' => 'https://libraryofcongress.github.io/data-exploration/',
                'status' => 'Active',
                'is_preset' => true,
            ]
        ];

        foreach ($apis as $api) {
            LibraryApi::updateOrCreate(['id' => $api['id']], $api);
        }
    }
}
